In [ ]:
import pandas as pd
import glob
from sqlalchemy import create_engine

In [37]:
# Lendo todos os arquivos da pasta data/* e juntando todos em um dataframe novo

#df_faturas = pd.read_csv("data/Fatura_2026-01-20.csv")

arquivos = glob.glob("data/*.csv")

dfs = [pd.read_csv(arquivo, sep=';') for arquivo in arquivos]

df_faturas = pd.concat(dfs)

df_faturas

# CRIANDO NOVO ARQUIVO CSV apenas com os dados necessários
colunas = [
    'Data de Compra',
    'Nome no Cartão',
    'Final do Cartão',
    'Categoria',
    'Descrição',
    'Parcela',
    'Valor (em R$)'
]

faturas_df = df_faturas[colunas]

faturas_df.to_csv("data_n/faturas-2026.csv", index=False)

print("Arquivo criado com sucesso!")

Arquivo criado com sucesso!

In [52]:
# Carregando os dados para o Data Warehouse
df_faturas = pd.read_csv("data_n/faturas-2026.csv")
df_faturas

"""
CREATE USER 'etl_user'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON cartaoaula.* TO 'etl_user'@'localhost';
FLUSH PRIVILEGES;
"""

engine = create_engine(
    "mysql+pymysql://etl_user:123456@localhost:3306/cartaoaula"
)

df_faturas['Data de Compra'] = pd.to_datetime(df_faturas['Data de Compra'],dayfirst=True)
df_faturas['Categoria'] = df_faturas['Categoria'].fillna('Não categorizado').replace('-', 'Não categorizado')

def tratar_parcelas(texto):
    if '/' in str(texto):
        p = texto.split('/')
        return int(p[0]), int(p[1])
    return 1, 1
df_faturas['num_parcela'], df_faturas['total_parcelas'] = zip(*df_faturas['Parcela'].apply(tratar_parcelas))

# --- CRIAÇÃO DAS DIMENSÕES ---

# DIM_TITULAR
dim_titular = df_faturas[['Nome no Cartão', 'Final do Cartão']].drop_duplicates().reset_index(drop=True)
dim_titular.columns = ['nome_titular', 'final_cartao']
dim_titular.index.name = 'id_titular'
dim_titular = dim_titular.reset_index()

# DIM_CATEGORIA
dim_categoria = df_faturas[['Categoria']].drop_duplicates().reset_index(drop=True)
dim_categoria.columns = ['nome_categoria']
dim_categoria.index.name = 'id_categoria'
dim_categoria = dim_categoria.reset_index()

# DIM_ESTABELECIMENTO
dim_estab = df_faturas[['Descrição']].drop_duplicates().reset_index(drop=True)
dim_estab.columns = ['nome_estabelecimento']
dim_estab.index.name = 'id_estabelecimento'
dim_estab = dim_estab.reset_index()

# DIM_DATA
dim_data = pd.DataFrame({'data': df_faturas['Data de Compra'].drop_duplicates()})

dim_data['dia'] = dim_data['data'].dt.day
dim_data['mes'] = dim_data['data'].dt.month
dim_data['ano'] = dim_data['data'].dt.year
dim_data['trimestre'] = dim_data['data'].dt.quarter
dim_data['dia_semana'] = dim_data['data'].dt.day_name()

dim_data.index.name = 'id_data'
dim_data = dim_data.reset_index()

# FATO

fato = df_faturas.merge(dim_titular, left_on=['Nome no Cartão', 'Final do Cartão'], right_on=['nome_titular', 'final_cartao']) \
               .merge(dim_categoria, left_on='Categoria', right_on='nome_categoria') \
               .merge(dim_estab, left_on='Descrição', right_on='nome_estabelecimento') \
               .merge(dim_data, left_on='Data de Compra', right_on='data')

fato_final = fato[['id_data', 'id_titular', 'id_categoria', 'id_estabelecimento', 
                   'num_parcela', 'total_parcelas', 'Valor (em R$)']]
fato_final.columns = ['id_data', 'id_titular', 'id_categoria', 'id_estabelecimento', 
                      'num_parcela', 'total_parcelas', 'valor_brl']

dim_titular.to_sql('dim_titular', engine, if_exists='append', index=False)
dim_categoria.to_sql('dim_categoria', engine, if_exists='append', index=False)
dim_estab.to_sql('dim_estabelecimento', engine, if_exists='append', index=False)
dim_data.to_sql('dim_data', engine, if_exists='append', index=False)
fato_final.to_sql('fato_transacao', engine, if_exists='append', index=False)

print("Data Warehouse atualizado com o Modelo Estrela completo!")

DatabaseError: Execution failed on sql 'INSERT INTO dim_titular (id_titular, nome_titular, final_cartao) VALUES (:id_titular, :nome_titular, :final_cartao)': (pymysql.err.IntegrityError) (1062, "Duplicate entry '0' for key 'PRIMARY'")
[SQL: INSERT INTO dim_titular (id_titular, nome_titular, final_cartao) VALUES (%(id_titular)s, %(nome_titular)s, %(final_cartao)s)]
[parameters: [{'id_titular': 0, 'nome_titular': 'VIN DIESEL', 'final_cartao': 1115}, {'id_titular': 1, 'nome_titular': 'VIN DIESEL', 'final_cartao': 1122}, {'id_titular': 2, 'nome_titular': 'CHARLIZE THERON', 'final_cartao': 1153}, {'id_titular': 3, 'nome_titular': 'BRIAN TYLER', 'final_cartao': 1114}, {'id_titular': 4, 'nome_titular': 'EVA MENDES', 'final_cartao': 1117}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [29]:
# CRIANDO A TABELA NO SQLITE
engine = create_engine("sqlite:///faturas-2026.db")

In [30]:
df = pd.read_csv("data_n/faturas-2026.csv")
df

try:
    df.to_sql('faturas-2026', con=engine, if_exists='replace', index=False)
    print("Sucesso! Dados exportados para a tabela faturas-2026 :)")
except Exception as e:
    print(f"Ocorreu algum erro ao exportar os dados :( {e}")

Sucesso! Dados exportados para a tabela faturas-2026 :)

In [13]:
# Total de transações por categoria
consulta_1 = " SELECT Categoria, count('Data de Compra') AS qtd_cat FROM 'faturas-2026' GROUP BY Categoria "
resultado_1 = pd.read_sql_query(consulta_1, engine)
resultado_1

                                            Categoria  qtd_cat
0                                                   -       11
1                   Assistência médica e odontológica       24
2                                          Associação       34
3                        Casa / Escritório Mobiliário        2
4                                  Consertos em Geral        1
5                                          Construção        1
6                             Departamento / Desconto       12
7                                         Educacional        2
8                                            Elétrico       37
9                                Empresa para empresa       20
10                                   Empresa serviços        2
11                                     Entretenimento       14
12                               Especialidade varejo       11
13                               Limpeza / Lavanderia        1
14                                   Marketing Direto        1
15                  Materiais de construção para casa        6
16                          Relacionados a Automotivo       18
17                     Restaurante / Lanchonete / Bar       12
18                                             Seguro        3
19                             Serviços Profissionais        3
20                       Serviços de telecomunicações       17
21                               Serviços financeiros        6
22                                  Serviços pessoais       10
23  Supermercados / Mercearia / Padarias / Lojas d...       76
24                                T&E Companhia aérea        2
25              TV por assinatura / Serviços de rádio        3
26                                         Transporte       20
27                                 Vestuário / Roupas       11

In [14]:
# Total de transações por usuário
consulta_2 = """ SELECT "Nome no Cartão", count(*) AS qtd_trans_user FROM 'faturas-2026' GROUP BY "Nome no Cartão" """
resultado_2 = pd.read_sql_query(consulta_2, engine)
resultado_2

    Nome no Cartão  qtd_trans_user
0      BRIAN TYLER              78
1  CHARLIZE THERON              82
2       EVA MENDES              46
3       VIN DIESEL             154

In [15]:
# Total de parcelas únicas
consulta_3 =""" SELECT Parcela, COUNT(*) AS qtd_unicas FROM 'faturas-2026' WHERE Parcela = 'Única' GROUP BY Parcela """
resultado_3 = pd.read_sql_query(consulta_3, engine)
resultado_3

  Parcela  qtd_unicas
0   Única         304

In [16]:
# Total de parcelas únicas por usuário
consulta_4 =""" SELECT "Nome no Cartão", COUNT(*) AS qtd_unicas FROM 'faturas-2026' WHERE Parcela = 'Única' GROUP BY "Nome no Cartão" """
resultado_4 = pd.read_sql_query(consulta_4, engine)
print(resultado_4)

    Nome no Cartão  qtd_unicas
0      BRIAN TYLER          70
1  CHARLIZE THERON          66
2       EVA MENDES          37
3       VIN DIESEL         131

In [17]:
from sqlalchemy import create_engine

engine = create_engine(
    'mysql+pymysql://root:masterkey@localhost:3306/business'
)